name: Push to Main Task

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Check
         run: |
          echo "Running ESLint"
          npx eslint .  # Replace with your ESLint command

      - name: Revert last commit
        if: failure()  # This step runs if the previous steps fail
        run: |
           git config --local user.email "ashfaqonly1@gmail.com"
          git config --local user.name "Ashfaq"
          git revert HEAD --no-edit
          git push origin main
