name: Pre-Merge Task

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Run ESLint
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "test"
          echo $SOURCE_BRANCH
          echo $TARGET_BRANCH
          exit 1
